config/routes.rb
Rails.application.routes.draw do

  resources :banks
  resources :truckingindustries
  
  resources :contacts do
    resources :payments
  end


  devise_for :users

  root 'pages#index'

  get 'office(/:id)', to: 'pages#office'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank.rb
class Bank < ApplicationRecord

    validates :name, presence: true
	
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
       
      else
        format.html { render :new }
        
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.fetch(:bank, {}).permit(:name, :bik, :cor_acc)
     
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.1.slim
= form_for @bank do |f|
  - if @bank.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bank.errors.count, "error")} prohibited this bank from being saved:"
      ul
        - @bank.errors.full_messages.each do |message|
          li = message


  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :bik
    = f.text_field :bik
  .field
    = f.label :cor_acc
    = f.text_field :cor_acc
  .actions = f.submit

app/views/banks/_form.html.slim
= simple_form_for @bank do |f|
 
  
  = f.input :name
  = f.input :bik
  = f.input :cor_acc
  = f.submit

app/views/banks/edit.html.slim
h1 Editing bank

== render 'form'

=> link_to 'Show', @bank
'|
=< link_to 'Back', banks_path

app/views/banks/index.html.slim
= link_to 'Back to', contacts_path

h1 Listing banks

table class="table table-info table-hover table-striped"
  thead
    tr class="table-success"
      th Name Bank
      th BIK
      th KPP
      th Address
      th
      th

  tbody
    - @banks.each do |bank|
      tr
        td = bank.name
        td = bank.bik
        td = bank.cor_acc
        td = link_to 'Show', bank
        td = link_to 'Edit', edit_bank_path(bank)
        td = link_to 'Destroy', bank, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Bank', new_bank_path

app/views/banks/new.html.slim
h1 New bank

== render 'form'

= link_to 'Back', banks_path

app/views/banks/show.html.slim
p#notice = notice

p 
  b Наименования банка 
  |#{@bank.name}
p Logo bank
p 
p 
  b БИК: 
  |#{@bank.bik}
p 
  b КПП: 
  |#{@bank.cor_acc}


=> link_to 'Edit', edit_bank_path(@bank)
'|
=< link_to 'Back', banks_path