config/routes.rb
Rails.application.routes.draw do

  resources :banks
  resources :truckingindustries
  
  resources :contacts do
    resources :payments
  end


  devise_for :users

  root 'pages#index'

  get 'office(/:id)', to: 'pages#office'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates  :inn, presence: true
  validates  :name, presence: true
  validates  :foo, presence: true

  belongs_to :user
  has_many   :payments, dependent: :destroy, validate: true
  validates_associated :payments
  
 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
    
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
   
       
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @payments = Payment.where('contact_id = ?', params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @payment = Payment.where(contact_id: @contact.id)
    @payment.each do |pay|
      pay.destroy
    end
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:foo, :name, :inn, :kpp, :ogrn, :legal_address, :postal_address, :contacts, :other)
    end

    
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.1.slim
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :foo
    = f.text_field :foo
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :inn
    = f.number_field :inn
  .field
    = f.label :kpp
    = f.number_field :kpp
  .field
    = f.label :ogrn
    = f.number_field :ogrn
  .field
    = f.label :legal_address
    = f.text_field :legal_address
  .field
    = f.label :postal_address
    = f.text_field :postal_address
  .field
    = f.label :contacts
    = f.text_field :contacts
  .field
    = f.label :other
    = f.text_field :other
  .actions = f.submit

app/views/contacts/_form.html.slim
= simple_form_for @contact do |f|
  = f.input :foo
  = f.input :name
  = f.input :inn
  = f.input :kpp
  = f.input :ogrn
  = f.input :legal_address
  = f.input :postal_address
  = f.input :contacts
  = f.input :other, as: :text
  = f.submit

app/views/contacts/edit.html.slim
h1 Редактирование карточки партнера

- if @contact.user_id == current_user.id
  == render 'form'
- else
  h2 Доступ закрыт

=> link_to 'Show', @contact
'|
=< link_to 'Back', contacts_path

app/views/contacts/index.html.slim
h1 Ваши контакты

center
  = link_to 'New Contact', new_contact_path, :class => "btn btn-outline-info"
br
br
br

table class="table table-info table-hover table-striped"
  thead
    tr class="table-success"
      th Foo
      th Name
      th Inn
      th Kpp
      th Ogrn
      th Legal address
      th Postal address
      th Contacts
      th Other
      th
      th
      th

  tbody
    - @contacts.each do |contact|
      - if contact.user_id == current_user.id
        tr
          td = contact.foo
          td = contact.name
          td = contact.inn
          td = contact.kpp
          td = contact.ogrn
          td = contact.legal_address
          td = contact.postal_address
          td = contact.contacts
          td =raw contact.other
          td = link_to 'Show', contact
          td = link_to 'Edit', edit_contact_path(contact)
          td = link_to 'Destroy', contact, data: { confirm: 'Are you sure?' }, method: :delete


br


                   
br
= link_to 'New Bank', new_bank_path          

app/views/contacts/new.html.slim
h1 New contact

== render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.slim
- if @contact.user_id == current_user.id
  p#notice = notice
  .container
    .row
      .col-md-7  
      
        p
          strong Форма собственности: 
          = @contact.foo
        p
          strong Название организации: 
          = @contact.name
        p
          strong ИНН: 
          = @contact.inn
        p
          strong КПП: 
          = @contact.kpp
        p
          strong ОГРН: 
          = @contact.ogrn
        p
          strong Юридический адрес: 
          = @contact.legal_address
        p
          strong Почтовый адрес: 
          = @contact.postal_address
        p
          strong Контакты: 
          = @contact.contacts
      div class="col-md-5 col-sm-5 notes"
        p
          strong Заметки: <br>
          =raw @contact.other
    


    br
  
  
    div class="col-7"
      table class="table table-info table-hover border table-striped"
        thead class="thead-primary"
          tr
            th Рассчетный счет
            th БИК
            th Корр. счет
            th БАНК
        tbody
          - @contact.payments.each do |item|
            tr
              td = item.number
              td = item.bik
              td = item.corr
              td = item.bank
              td = link_to 'Изменить', [:edit, item.contact, item]
              td = link_to 'Удалить', [item.contact, item], method: :delete, data: { confirm: 'Вы уверены?'}

    br

      = link_to 'Добавить расчетный счет', new_contact_payment_path(@contact)
      br
      br

    
      => link_to 'Edit', edit_contact_path(@contact)
      '|
      =< link_to 'Back', contacts_path
- else
  h2 Доступ закрыт