config/routes.rb
Rails.application.routes.draw do

  resources :banks
  resources :truckingindustries
  
  resources :contacts do
    resources :payments
  end


  devise_for :users

  root 'pages#index'

  get 'office(/:id)', to: 'pages#office'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/truckingindustry.rb
class Truckingindustry < ApplicationRecord
end

app/controllers/truckingindustries_controller.rb
class TruckingindustriesController < ApplicationController
  before_action :set_truckingindustry, only: [:show, :edit, :update, :destroy]

  # GET /truckingindustries
  # GET /truckingindustries.json
  def index
    @truckingindustries = Truckingindustry.all
  end

  # GET /truckingindustries/1
  # GET /truckingindustries/1.json
  def show
  end

  # GET /truckingindustries/new
  def new
    @truckingindustry = Truckingindustry.new
  end

  # GET /truckingindustries/1/edit
  def edit
  end

  # POST /truckingindustries
  # POST /truckingindustries.json
  def create
    @truckingindustry = Truckingindustry.new(truckingindustry_params)
    
    @truckingindustry.coastofroad = (truckingindustry_params['priceofroad'].to_i * truckingindustry_params['rm_weight'].to_i)/1000

    if @truckingindustry.add_weight=""
      @truckingindustry.add_weight=truckingindustry_params['rm_weight']
    end
    
    respond_to do |format|
      if @truckingindustry.save
        format.html { redirect_to @truckingindustry, notice: 'Truckingindustry was successfully created.' }
        format.json { render :show, status: :created, location: @truckingindustry }
      else
        format.html { render :new }
        format.json { render json: @truckingindustry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /truckingindustries/1
  # PATCH/PUT /truckingindustries/1.json
  def update
    respond_to do |format|
      if @truckingindustry.update(truckingindustry_params)
        format.html { redirect_to @truckingindustry, notice: 'Truckingindustry was successfully updated.' }
        format.json { render :show, status: :ok, location: @truckingindustry }
      else
        format.html { render :edit }
        format.json { render json: @truckingindustry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /truckingindustries/1
  # DELETE /truckingindustries/1.json
  def destroy
    @truckingindustry.destroy
    respond_to do |format|
      format.html { redirect_to truckingindustries_url, notice: 'Truckingindustry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truckingindustry
      @truckingindustry = Truckingindustry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truckingindustry_params
      params.require(:truckingindustry).permit(:order, :price_buy, :price_sale, :add_weight, :rm_weight, :supplier, :buyer, :autocarrier, :numberauto, :priceofroad, :coastofroad)
    end
end

app/helpers/truckingindustries_helper.rb
module TruckingindustriesHelper
end

app/helpers/truckingindustry_helper.rb
module TruckingindustryHelper
end

app/views/truckingindustries/_form.html.slim
= simple_form_for(@truckingindustry) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :order
    = f.input :price_buy
    = f.input :price_sale
    = f.input :supplier
    = f.input :buyer
    = f.input :add_weight
    = f.input :rm_weight
    = f.input :autocarrier
    = f.input :numberauto
    = f.input :priceofroad
   

  .form-actions
    = f.button :submit

app/views/truckingindustries/edit.html.slim
h1 Editing truckingindustry

== render 'form'

=> link_to 'Show', @truckingindustry
'|
=< link_to 'Back', truckingindustries_path

app/views/truckingindustries/index.html.slim
h2 Грузоперевозки
center
  = link_to 'Добавыить запись', new_truckingindustry_path, :class => 'btn btn-outline-success'
br
br
br
table class="table table-info table-hover table-striped"
  thead 
    tr class="table-success"
      th Товар
      th Цена закупки
      th Цена продажи
      th Поставщик
      th Покупатель
      th Приход
      th Расход
      th Перевозчик
      th Номер авто
      th Цена перевозки, т/км
      th Стоимость перевозки, р.
      th
      th
      th

  tbody
    - @truckingindustries.each do |truckingindustry|
      tr
        td = truckingindustry.order
        td = truckingindustry.price_buy
        td = truckingindustry.price_sale
        td = truckingindustry.supplier
        td = truckingindustry.buyer
        td = truckingindustry.add_weight
        td = truckingindustry.rm_weight
        td = truckingindustry.autocarrier
        td = truckingindustry.numberauto
        td = truckingindustry.priceofroad
        td = truckingindustry.coastofroad
        td = link_to 'Show', truckingindustry
        td = link_to 'Edit', edit_truckingindustry_path(truckingindustry)
        td = link_to 'Destroy', truckingindustry, data: { confirm: 'Are you sure?' }, method: :delete

br

app/views/truckingindustries/new.html.slim
h1 New truckingindustry

== render 'form'

= link_to 'Back', truckingindustries_path

app/views/truckingindustries/show.html.slim
p#notice = notice

p
  strong Order:
  = @truckingindustry.order
p
  strong Price-buy:
  = @truckingindustry.price_buy
p
  strong Price-sale:
  = @truckingindustry.price_sale
p
  strong Supplier:
  = @truckingindustry.supplier
p
  strong Buyer:
  = @truckingindustry.buyer
p
  strong Autocarrier:
  = @truckingindustry.autocarrier
p
  strong Numberauto:
  = @truckingindustry.numberauto
p
  strong Priceofroad:
  = @truckingindustry.priceofroad
p
  strong Coastofroad:
  = @truckingindustry.coastofroad

=> link_to 'Edit', edit_truckingindustry_path(@truckingindustry)
'|
=< link_to 'Back', truckingindustries_path